# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAOncKwEm1F9c5LrT7HMNmRMYX8-fAoqpc6YyTu9X";
    path = fetchzip {
      url = "https://codeload.github.com/wolfpld/tracy/tar.gz/refs/tags/v0.13.1";
      hash = "sha256-D4aQ5kSfWH9qEUaithR0W/E5pN5on0n9YoBHeMggMSE=";
    };
  }
  {
    name = "diffz-0.0.1-G2tlISvOAQDORzPTSxDgiKwlHuADKeJMdJrw4kRfLufj";
    path = fetchzip {
      url = "https://codeload.github.com/ziglibs/diffz/tar.gz/aac8aa99c436ab8277b0711922aad062c0167b12";
      hash = "sha256-GQ4iCZSSpVvdDQteoi02keLSqSoDOSQPH8eihum++Z0=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJiDLAAB98m3uYUzatrTb2mO2fpvwx2zpSroEtfbO";
    path = fetchzip {
      url = "https://codeload.github.com/ziglibs/known-folders/tar.gz/6da0d0c41b78b9ed2d34fa364fcb81b5ebece6c4";
      hash = "sha256-F17Ivvsyyla2CBIh+kImc1O3AtD2yTDAGamzMVbVzuw=";
    };
  }
  {
    name = "lsp_kit-0.1.0-bi_PLwc2DACoR7VTz_qKFXUvtx7veHvWcTQvP9pDFLpk";
    path = fetchzip {
      url = "https://codeload.github.com/zigtools/lsp-kit/tar.gz/d148676ace1eaecf3c703ce7d350d0e94e502ed7";
      hash = "sha256-O4LSGT/0/2gFbXcOt0Panj4a26J5gA1NkmO0+7PfkJg=";
    };
  }
]
